# Generated by Django 3.2.7 on 2022-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='usertype',
            new_name='user_type',
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
