# Generated by Django 3.2.7 on 2022-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220313_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
